### ISSUE TITLE
Https access to pimatic

### ISSUE THREAD

**Issue by made1990** [petschni/pimatic#8]
Hi,
how to enable https access to the pimatic?

What I did:
- created certificates with the ssl-config script from pimatic (https://pimatic.teamemo.com/Guide/Remote-Access-and-SSL)
- enabled https in pimatic config.json
- added a port mapping to the docker container ( port 2000 to port 443)  // port 2000 is just random
- added port forwarding into my fritzbox router ( port 443 to port 2000 of my Synology NAS running docker)

I now want to access my pimatic via https from the internet via dyndns, but I get an error in the browser:

"The security certificate presented by this website is not secure.
Security certificate problems may indicate an attempt to fool you or intercept any data you send to the server"

Any idea on that?

**Comment by petschni** [comment]
Maybe that is because the certificate is not verified? But it sounds more like a general issue than specific to my docker image, or? I would suggest to open an issue with pimatic directly.
